name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build (${{ matrix.os }}-${{ matrix.arch }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
          - os: linux
            arch: arm64
          - os: darwin
            arch: amd64
          - os: darwin
            arch: arm64
          - os: windows
            arch: amd64

    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25"

      - name: Get version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build binary and package
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
          CGO_ENABLED: 0
        run: |
          BINARY_NAME="howtfdoi-${{ steps.version.outputs.VERSION }}-${{ matrix.os }}-${{ matrix.arch }}"
          if [ "${{ matrix.os }}" = "windows" ]; then
            BINARY_NAME="${BINARY_NAME}.exe"
          fi
          go build -ldflags="-s -w" -o "${BINARY_NAME}"

          # Create tarball (except for Windows)
          if [ "${{ matrix.os }}" != "windows" ]; then
            tar czf "${BINARY_NAME}.tar.gz" "${BINARY_NAME}"
            echo "ASSET=${BINARY_NAME}.tar.gz" >> $GITHUB_ENV
          else
            zip "${BINARY_NAME}.zip" "${BINARY_NAME}"
            echo "ASSET=${BINARY_NAME}.zip" >> $GITHUB_ENV
          fi

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: howtfdoi-${{ steps.version.outputs.VERSION }}-${{ matrix.os }}-${{ matrix.arch }}
          path: ${{ env.ASSET }}

  publish:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Extract version
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: List downloaded artifacts (debug)
        run: ls -la artifacts || true

      - name: Create Release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  homebrew:
    name: Update Homebrew Formula
    needs: publish
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Extract version
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Homebrew bump formula
        uses: mislav/bump-homebrew-formula-action@v3
        if: "!contains(github.ref, '-')" # Skip pre-releases
        with:
          formula-name: howtfdoi
          homebrew-tap: NeckBeardPrince/homebrew-tap
          download-url: https://github.com/${{ github.repository }}/archive/${{ github.ref_name }}.tar.gz
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
